### ISSUE TITLE
Upload also the KeyedVectors file

### ISSUE THREAD

**Issue by RicardoHS** [aitoralmeida/spanish_word2vec#1]
Is a much smaller file so if the only thing you want are the vectors itself its more easy to download than the NN Model.

IC: https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.KeyedVectors

**Comment by aitoralmeida** [comment]
We have added the keyed vector file to Zenodo. Thanks for the suggestion.
